import { BlendRC, ChannelMixerRC, ColorSpaceConversionRC, ContrastRC, HueRC, ReplaceColorRC, SaturationRC, WhiteBalanceRC } from './artistic';
import {
  PositionBlock,
  NormalBlock,
  BaseColorBlock,
  TangentBlock,
  AOBlock,
  SmoothnessBlock,
  MetallicBlock,
  EmissionBlock,
  NormalTangentSpaceBlock,
  CustomInterpolatorBlock,
  AlphaBlock,
  AlphaClipBlock,
  CoatMaskBlock,
  CoatSmoothnessBlock,
} from './blocks';
import { CombineRC, FlipRC, SplitRC, SwizzleRC } from './channel';
import {
  Vec2RC,
  FloatRC,
  Vec3RC,
  Vec4RC,
  ConstantRC,
  ColorRC,
  TimeRC,
  ParameterRC,
  VaryingRC,
  Texture2DAssetRC,
  SampleTexture2DRC,
  UVRC,
  NormalRC,
  PositionRC,
  ViewVectorRC,
  ViewDirectionRC,
  TexelSizeRC,
  TransformationMatrixRC,
  Matrix4x4RC,
  Matrix2x2RC,
  Matrix3x3RC,
  SamplerStateRC,
} from './input';
import {
  AbsoluteRC,
  AddRC,
  ArccosineRC,
  Arctangent2RC,
  ArctangentRC,
  CeilingRC,
  ClampRC,
  CosineRC,
  CrossProductRC,
  DDXRC,
  DDXYRC,
  DDYRC,
  DegreesToRadiansRC,
  DistanceRC,
  DivideRC,
  DotProductRC,
  FloorRC,
  FractionRC,
  FresnelEffectRC,
  HyperbolicCosineRC,
  HyperbolicSineRC,
  HyperbolicTangentRC,
  InverseLerpRC,
  LengthRC,
  LerpRC,
  LogRC,
  MaximumRC,
  MinimumRC,
  ModuloRC,
  MultiplyRC,
  NegateRC,
  NoiseSineWaveRC,
  NormalizeRC,
  OneMinusRC,
  PosterizeRC,
  PowerRC,
  ProjectionRC,
  RadiansToDegreesRC,
  RandomRangeRC,
  ReciprocalRC,
  ReciprocalSquareRootRC,
  ReflectionRC,
  RemapRC,
  RotateAboutAxisRC,
  RoundRC,
  SaturateRC,
  SawtoothWaveRC,
  SignRC,
  SineRC,
  SmoothstepRC,
  SphereMaskRC,
  SquareRootRC,
  SquareWaveRC,
  StepRC,
  SubtractRC,
  TangentRC,
  TransformRC,
  TriangleWaveRC,
  TruncateRC,
} from './math';
import { FragmentRC, OutputRC, VertexRC } from './output';
import {
  CheckerboardRC,
  EllipseRC,
  GradientNoiseRC,
  PolygonRC,
  RectangleRC,
  RoundedPolygonRC,
  RoundedRectangleRC,
  SimpleNoiseRC,
  VoronoiRC,
} from './procedural';
import { CustomFunctionRC, PreviewNumberRC, PreviewRC, SubGraphRC } from './utility';
import { PolarCoordinatesRC, RotateRC, TilingAndOffsetRC, TwirlRC } from './uv';

export const initShaderGraphComponents = () => [
  new Vec2RC(),
  new AddRC(),
  new FloatRC(),
  new Vec3RC(),
  new Vec4RC(),
  new FragmentRC(),
  new PositionBlock(),
  new NormalBlock(),
  new VertexRC(),
  new BaseColorBlock(),
  new TangentBlock(),
  new AOBlock(),
  new SmoothnessBlock(),
  new MetallicBlock(),
  new EmissionBlock(),
  new NormalTangentSpaceBlock(),
  new CustomInterpolatorBlock(),
  new ConstantRC(),
  new ColorRC(),
  new TimeRC(),
  new ParameterRC(),
  new SubtractRC(),
  new DivideRC(),
  new VaryingRC(),
  new Texture2DAssetRC(),
  new SampleTexture2DRC(),
  new UVRC(),
  new AlphaBlock(),
  new AlphaClipBlock(),
  new SineRC(),
  new CosineRC(),
  new ArccosineRC(),
  new ArctangentRC(),
  new Arctangent2RC(),
  new HyperbolicCosineRC(),
  new HyperbolicSineRC(),
  new HyperbolicTangentRC(),
  new DegreesToRadiansRC(),
  new RadiansToDegreesRC(),
  new TangentRC(),
  new PowerRC(),
  new SquareRootRC(),
  new AbsoluteRC(),
  new LengthRC(),
  new LogRC(),
  new ModuloRC(),
  new NegateRC(),
  new NormalizeRC(),
  new PosterizeRC(),
  new ReciprocalRC(),
  new ReciprocalSquareRootRC(),
  new DDXRC(),
  new DDYRC(),
  new LerpRC(),
  new SmoothstepRC(),
  new InverseLerpRC(),
  new ClampRC(),
  new FractionRC(),
  new MinimumRC(),
  new MaximumRC(),
  new OneMinusRC(),
  new RemapRC(),
  new SaturateRC(),
  new RandomRangeRC(),
  new CeilingRC(),
  new FloorRC(),
  new RoundRC(),
  new SignRC(),
  new TruncateRC(),
  new StepRC(),
  new CrossProductRC(),
  new DistanceRC(),
  new DotProductRC(),
  new FresnelEffectRC(),
  new ProjectionRC(),
  new ReflectionRC(),
  new RotateAboutAxisRC(),
  new SphereMaskRC(),
  new NoiseSineWaveRC(),
  new SquareWaveRC(),
  new SawtoothWaveRC(),
  new TriangleWaveRC(),
  new DDXYRC(),
  new NormalRC(),
  new PositionRC(),
  new ViewVectorRC(),
  new ViewDirectionRC(),
  new CombineRC(),
  new SplitRC(),
  new SwizzleRC(),
  new FlipRC(),
  new CheckerboardRC(),
  new GradientNoiseRC(),
  new SimpleNoiseRC(),
  new VoronoiRC(),
  new EllipseRC(),
  new PolygonRC(),
  new RectangleRC(),
  new RoundedPolygonRC(),
  new RoundedRectangleRC(),
  new TexelSizeRC(),
  new MultiplyRC(),
  new TransformationMatrixRC(),
  new Matrix4x4RC(),
  new Matrix3x3RC(),
  new Matrix2x2RC(),
  new TransformRC(),
  new PreviewRC(),
  new CustomFunctionRC(),
  new CoatMaskBlock(),
  new CoatSmoothnessBlock(),
  new OutputRC(),
  new SubGraphRC(),
  new ChannelMixerRC(),
  new ContrastRC(),
  new HueRC(),
  new ReplaceColorRC(),
  new SaturationRC(),
  new WhiteBalanceRC(),
  new BlendRC(),
  new ColorSpaceConversionRC(),
  new SamplerStateRC(),
  new PreviewNumberRC(),
  new TilingAndOffsetRC(),
  new PolarCoordinatesRC(),
  new RotateRC(),
  new TwirlRC(),
];
